config/routes.rb
Rails.application.routes.draw do
  root to: 'doctors#index'
  # For details on the DSL available within this file, see http s://guides.rubyonrails.org/routing.html
  resources :doctors, only: [:index, :show, :new] do
    resources :appointments, only: [:new, :create]
  end
  resources :appointments, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor

   validates :date, :time, :user_name, presence: true
   validates :email, presence: true, format: { with: /\A.*@.*\.com\z/ }
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	has_many :appointments, dependent: :destroy

	validates :forename, :surname, :specialty, :address, :description, presence: true
	geocoded_by :address
	after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
	before_action :set_doctor, except: [:index, :show, :destroy]

	def new
		@appointment = Appointment.new
		@doctor = set_doctor
	end

	def index
		@appointments = Appointment.all
	end

	def show
    @appointment = Appointment.find(params[:id])
    @doctor = @appointment.doctor
  end

	def create
    @appointment = Appointment.new(appointment_params)
    @appointment.doctor = @doctor
    if @appointment.save
      redirect_to appointment_path(@appointment)
    else
      render :new
    end
  end

	private

  def set_doctor
    @doctor = Doctor.find(params[:doctor_id])
  end

  def appointment_params
    params.require(:appointment).permit(:user_name, :email, :date, :time, :nhs_number)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
	def new
		@doctor = Doctor.new
	end

	def index
		@doctors = Doctor.all

	  @markers = @doctors.geocoded.map do |doctor|
    {
      lat: doctor.latitude,
      lng: doctor.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { doctor: doctor })
    }
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/new.html.erb
<div class="container">
	<div class="pb-5 px-3">
	<h1>Book your appointment with dr <%= @doctor.surname %></h1>
	<h4>Please fill out the form below to create your appointment</h4>
		<%= simple_form_for [ @doctor, @appointment ] do |f| %>
		  <%= "Select date and timeslot" %>
		  <%= f.input :date, html5: true %>
		  <%= f.input :time, html5: true %>
		  <%= f.input :user_name, label: "Full name" %>
		  <%= f.input :email, label: "Email address" %>
		  <%= f.input :nhs_number, label: "NHS Number (optional)" %>
		  <%= f.submit value: "Book Appointment", class: "btn btn-dark" %>
		<% end %>
	<%= link_to 'Back', doctors_path(@doctor) %>
	</div>
</div>

app/views/appointments/show.html.erb
<div class="container">
	<div class="pb-5 px-3">
		<h1>Appointment booked</h1>
		<h6>Thanks, you've made a booking with...</h6>
		<h2>Dr. <%= @appointment.doctor.forename %> <%= @appointment.doctor.surname %></h2>
		<h4><%= @appointment.doctor.specialty %></h4>
			<ul style="list-style: circle">
				<li><%= @appointment.doctor.address %></li>
				<li><%= @appointment.doctor.description %></li>
				<li><%= @appointment.date %></li><li><%= @appointment.time %></li>
			</ul>
		<h6>We've sent a booking confirmation to the email address you provided.</h6>
		<%= link_to 'Back', doctors_path(@doctor), class: "btn btn-dark" %>
	</div>
</div>

app/views/doctors/_info_window.html.erb
<h2>Dr. <%= doctor.forename %> <%= doctor.surname %></h2>
<h4><%= doctor.specialty %></h4>
<ul style="list-style: circle">
	<li><%= doctor.address %></li>
	<li><%= doctor.description %></li>
</ul>
<p><%= link_to "Book appointment", new_doctor_appointment_path(doctor), class: "btn btn-dark" %></p>

app/views/doctors/index.html.erb
<p><div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geolocation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-white">
    <a class="navbar-brand" href="/">Doc.ly</a>
      <ul class="navbar-nav">
        <li class="navbar-nav navbar-right active">
          <a class="nav-link" href="#">Home</a>
        </li>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>